// eslint-disable-next-line import/extensions
import { defineFlatConfigs } from "../.nuxt/eslint.config.mjs";

export default defineFlatConfigs({
    files: ["**/*.{js,jsx,ts,tsx,vue}"],
    rules: {
        "curly": ["error", "all"],
        "eqeqeq": [
            "error",
            "always",
            { null: "never" },
        ],
        "no-var": ["error"],
        "prefer-const": ["error", { destructuring: "all" }],
        "prefer-arrow-callback": ["error"],
        "no-param-reassign": ["error", { props: true }],
        "no-console": ["warn", { allow: ["warn", "error"] }],
        "no-debugger": ["error"],
        "no-undef": ["error"],
        "no-unused-expressions": ["error", { allowShortCircuit: true, allowTernary: true }],
        "default-case": ["error"],
        "no-case-declarations": ["error"],
        "operator-linebreak": "off",

        // Additional ESLint rules (commented out with default values)
        // "accessor-pairs": [],
        // "array-callback-return": [],
        // "arrow-body-style": [],
        // "block-scoped-var": [],
        // "camelcase": [],
        // "capitalized-comments": [],
        // "class-methods-use-this": [],
        // "complexity": [],
        // "consistent-return": [],
        // "consistent-this": [],
        // "default-case-last": [],
        // "default-param-last": [],
        // "dot-notation": [],
        // "func-name-matching": [],
        // "func-names": [],
        // "func-style": [],
        // "grouped-accessor-pairs": [],
        // "guard-for-in": [],
        // "id-denylist": [],
        // "id-length": [],
        // "id-match": [],
        // "init-declarations": [],
        // "logical-assignment-operators": [],
        // "max-classes-per-file": [],
        // "max-depth": [],
        // "max-lines": [],
        // "max-lines-per-function": [],
        // "max-nested-callbacks": [],
        // "max-params": [],
        // "max-statements": [],
        // "new-cap": [],
        // "no-alert": [],
        // "no-await-in-loop": [],
        // "no-bitwise": [],
        // "no-caller": [],
        // "no-constructor-return": [],
        // "no-continue": [],
        // "no-div-regex": [],
        // "no-duplicate-imports": [],
        // "no-else-return": [],
        // "no-empty-function": [],
        // "no-eq-null": [],
        // "no-eval": [],
        // "no-extend-native": [],
        // "no-extra-bind": [],
        // "no-extra-label": [],
        // "no-implicit-coercion": [],
        // "no-implicit-globals": [],
        // "no-implied-eval": [],
        // "no-inline-comments": [],
        // "no-inner-declarations": [],
        // "no-invalid-this": [],
        // "no-iterator": [],
        // "no-label-var": [],
        // "no-labels": [],
        // "no-lone-blocks": [],
        // "no-lonely-if": [],
        // "no-loop-func": [],
        // "no-magic-numbers": [],
        // "no-multi-assign": [],
        // "no-multi-str": [],
        // "no-negated-condition": [],
        // "no-nested-ternary": [],
        // "no-new": [],
        // "no-new-func": [],
        // "no-new-wrappers": [],
        // "no-object-constructor": [],
        // "no-octal-escape": [],
        // "no-plusplus": [],
        // "no-promise-executor-return": [],
        // "no-proto": [],
        // "no-restricted-exports": [],
        // "no-restricted-globals": [],
        // "no-restricted-imports": [],
        // "no-restricted-properties": [],
        // "no-restricted-syntax": [],
        // "no-return-assign": [],
        // "no-script-url": [],
        // "no-self-compare": [],
        // "no-sequences": [],
        // "no-shadow": [],
        // "no-template-curly-in-string": [],
        // "no-ternary": [],
        // "no-throw-literal": [],
        // "no-unassigned-vars": [],
        // "no-undef-init": [],
        // "no-undefined": [],
        // "no-underscore-dangle": [],
        // "no-unmodified-loop-condition": [],
        // "no-unneeded-ternary": [],
        // "no-unreachable-loop": [],
        // "no-use-before-define": [],
        // "no-useless-assignment": [],
        // "no-useless-call": [],
        // "no-useless-computed-key": [],
        // "no-useless-concat": [],
        // "no-useless-rename": [],
        // "no-useless-return": [],
        // "no-void": [],
        // "no-warning-comments": [],
        // "object-shorthand": [],
        // "one-var": [],
        // "operator-assignment": [],
        // "prefer-destructuring": [],
        // "prefer-exponentiation-operator": [],
        // "prefer-named-capture-group": [],
        // "prefer-numeric-literals": [],
        // "prefer-object-has-own": [],
        // "prefer-object-spread": [],
        // "prefer-promise-reject-errors": [],
        // "prefer-regex-literals": [],
        // "prefer-template": [],
        // "radix": [],
        // "require-atomic-updates": [],
        // "require-await": [],
        // "require-unicode-regexp": [],
        // "sort-imports": [],
        // "sort-keys": [],
        // "sort-vars": [],
        // "strict": [],
        // "symbol-description": [],
        // "unicode-bom": [],
        // "vars-on-top": [],
        // "yoda": [],
    },
});