// eslint-disable-next-line import/extensions
import { defineFlatConfigs } from "../.nuxt/eslint.config.mjs";

export default defineFlatConfigs({
    rules: {
        "@stylistic/array-bracket-newline": ["warn", { multiline: true, minItems: 3 }],
        "@stylistic/array-element-newline": ["warn", { consistent: true, multiline: true, minItems: 3 }],
        "@stylistic/curly-newline": ["warn", { consistent: true, multiline: true }],
        "@stylistic/function-call-argument-newline": ["warn", "consistent"],
        "@stylistic/function-call-spacing": ["warn", "never"],
        "@stylistic/function-paren-newline": "off",
        "@stylistic/implicit-arrow-linebreak": ["warn", "beside"],
        "@stylistic/line-comment-position": "off",
        "@stylistic/lines-around-comment": "off",
        "@stylistic/multiline-comment-style": "off",
        "@stylistic/no-confusing-arrow": ["warn", { allowParens: true, onlyOneSimpleParam: true }],
        "@stylistic/no-extra-semi": "error",
        "@stylistic/nonblock-statement-body-position": ["warn", "beside"],
        "@stylistic/object-curly-newline": [
            "warn",
            {
                ObjectExpression: { multiline: true },
                ObjectPattern: { multiline: true },
                ImportDeclaration: "never",
                ExportDeclaration: { multiline: true, minProperties: 3 },
                TSTypeLiteral: { multiline: true, minProperties: 3 },
                TSInterfaceBody: { multiline: true, minProperties: 3 },
                TSEnumBody: { multiline: true, minProperties: 3 },
            },
        ],
        "@stylistic/object-property-newline": "off",
        "@stylistic/one-var-declaration-per-line": ["warn", "initializations"],
        "@stylistic/switch-colon-spacing": ["warn", { before: false, after: true }],
        "@stylistic/wrap-regex": "off",
        "@stylistic/newline-per-chained-call": ["warn", { ignoreChainWithDepth: 4 }],
        "@stylistic/indent": ["warn", 4],
        "@stylistic/brace-style": [
            "warn",
            "allman",
            { allowSingleLine: false },
        ],
        "@stylistic/block-spacing": ["warn", "always"],
        "@stylistic/array-bracket-spacing": ["warn", "never"],
        "@stylistic/object-curly-spacing": ["warn", "always"],
        "@stylistic/comma-spacing": ["warn", { before: false, after: true }],
        "@stylistic/comma-style": ["warn", "last"],
        "@stylistic/comma-dangle": [
            "warn",
            {
                arrays: "always-multiline",
                objects: "always-multiline",
                imports: "always-multiline",
                exports: "always-multiline",
                functions: "never",
            },
        ],
        "@stylistic/semi": ["error", "always"],
        "@stylistic/semi-style": ["error", "last"],
        "@stylistic/semi-spacing": ["warn", { before: false, after: true }],
        "@stylistic/no-trailing-spaces": ["warn"],
        "@stylistic/eol-last": ["warn", "never"],
        "@stylistic/linebreak-style": "off",
        "@stylistic/max-len": "off",
        "@stylistic/lines-between-class-members": "off",
        "@stylistic/quotes": [
            "warn",
            "double",
            { avoidEscape: true, allowTemplateLiterals: "always" },
        ],
        "@stylistic/spaced-comment": ["warn", "always"],
        "@stylistic/space-before-blocks": "off", // Allman brace style renders this rule ineffective
        "@stylistic/space-before-function-paren": ["warn", { anonymous: "never", named: "never", asyncArrow: "always" }],
        "@stylistic/space-infix-ops": ["warn"],
        "@stylistic/keyword-spacing": ["warn", { before: true, after: true }],
        "@stylistic/type-annotation-spacing": ["warn", { before: true, after: true }],
        "@stylistic/padding-line-between-statements": [
            "warn",
            {
                blankLine: "any", prev: [
                    "const",
                    "let",
                    "var",
                    "function",
                    "class",
                    "export",
                ], next: "*",
            },
            { blankLine: "always", prev: "*", next: ["return"] },
        ],

        // JSX is not allowed to be used in this project, thus the rules can be force disabled
        "@stylistic/jsx-child-element-spacing": "off",
        "@stylistic/jsx-closing-bracket-location": "off",
        "@stylistic/jsx-closing-tag-location": "off",
        "@stylistic/jsx-curly-brace-presence": "off",
        "@stylistic/jsx-curly-newline": "off",
        "@stylistic/jsx-curly-spacing": "off",
        "@stylistic/jsx-equals-spacing": "off",
        "@stylistic/jsx-first-prop-new-line": "off",
        "@stylistic/jsx-function-call-newline": "off",
        "@stylistic/jsx-indent-props": "off",
        "@stylistic/jsx-max-props-per-line": "off",
        "@stylistic/jsx-newline": "off",
        "@stylistic/jsx-one-expression-per-line": "off",
        "@stylistic/jsx-pascal-case": "off",
        "@stylistic/jsx-quotes": "off",
        "@stylistic/jsx-self-closing-comp": "off",
        "@stylistic/jsx-sort-props": "off",
        "@stylistic/jsx-tag-spacing": "off",
        "@stylistic/jsx-wrap-multilines": "off",
    },
});