import typescriptParser from "@typescript-eslint/parser";

// eslint-disable-next-line import/extensions
import { defineFlatConfigs } from "../.nuxt/eslint.config.mjs";

export default defineFlatConfigs({
    files: ["**/*.{ts,tsx,vue}"],
    languageOptions: {
        parser: typescriptParser,
        parserOptions: {
            projectService: true,
            tsconfigRootDir: process.cwd(),
            extraFileExtensions: [".vue"],
        },
    },
    rules: {
        "@typescript-eslint/explicit-function-return-type": ["warn", { allowExpressions: true }],
        "@typescript-eslint/explicit-module-boundary-types": "warn",
        "@typescript-eslint/no-unused-vars": ["error", { args: "none", ignoreRestSiblings: true }],
        "@typescript-eslint/no-explicit-any": "warn",
        "@typescript-eslint/no-shadow": "error",
        "@typescript-eslint/no-redeclare": "error",
        "@typescript-eslint/no-empty-function": "warn",
        "@typescript-eslint/no-useless-constructor": "error",
        "@typescript-eslint/consistent-type-definitions": ["warn", "interface"],
        "@typescript-eslint/member-ordering": "warn",
        "@typescript-eslint/explicit-member-accessibility": ["warn", { accessibility: "explicit" }],
        "@typescript-eslint/naming-convention": [
            "warn",
            { selector: "typeLike", format: ["PascalCase"] },
            { selector: "variable", format: ["camelCase", "UPPER_CASE"], leadingUnderscore: "allow" },
            { selector: "function", format: ["camelCase", "PascalCase"] },
            { selector: "parameter", format: ["camelCase"], leadingUnderscore: "allow" },
            { selector: "property", format: ["camelCase", "PascalCase"], leadingUnderscore: "allow" },
            { selector: "enumMember", format: ["PascalCase"] },
        ],

        // Additional TypeScript rules (commented out with default values)
        // "@typescript-eslint/adjacent-overload-signatures": [],
        // "@typescript-eslint/array-type": [],
        // "@typescript-eslint/await-thenable": [],
        // "@typescript-eslint/ban-tslint-comment": [],
        // "@typescript-eslint/class-literal-property-style": [],
        // "@typescript-eslint/class-methods-use-this": [],
        // "@typescript-eslint/consistent-generic-constructors": [],
        // "@typescript-eslint/consistent-indexed-object-style": [],
        // "@typescript-eslint/consistent-return": [],
        // "@typescript-eslint/consistent-type-assertions": [],
        // "@typescript-eslint/consistent-type-exports": [],
        // "@typescript-eslint/default-param-last": [],
        // "@typescript-eslint/dot-notation": [],
        // "@typescript-eslint/init-declarations": [],
        // "@typescript-eslint/max-params": [],
        // "@typescript-eslint/method-signature-style": [],
        // "@typescript-eslint/no-array-delete": [],
        // "@typescript-eslint/no-base-to-string": [],
        // "@typescript-eslint/no-confusing-non-null-assertion": [],
        // "@typescript-eslint/no-confusing-void-expression": [],
        // "@typescript-eslint/no-deprecated": [],
        // "@typescript-eslint/no-dupe-class-members": [],
        // "@typescript-eslint/no-duplicate-type-constituents": [],
        // "@typescript-eslint/no-floating-promises": [],
        // "@typescript-eslint/no-for-in-array": [],
        // "@typescript-eslint/no-implied-eval": [],
        // "@typescript-eslint/no-inferrable-types": [],
        // "@typescript-eslint/no-invalid-this": [],
        // "@typescript-eslint/no-loop-func": [],
        // "@typescript-eslint/no-magic-numbers": [],
        // "@typescript-eslint/no-meaningless-void-operator": [],
        // "@typescript-eslint/no-misused-promises": [],
        // "@typescript-eslint/no-misused-spread": [],
        // "@typescript-eslint/no-mixed-enums": [],
        // "@typescript-eslint/no-redundant-type-constituents": [],
        // "@typescript-eslint/no-restricted-imports": [],
        // "@typescript-eslint/no-restricted-types": [],
        // "@typescript-eslint/no-unnecessary-boolean-literal-compare": [],
        // "@typescript-eslint/no-unnecessary-condition": [],
        // "@typescript-eslint/no-unnecessary-parameter-property-assignment": [],
        // "@typescript-eslint/no-unnecessary-qualifier": [],
        // "@typescript-eslint/no-unnecessary-template-expression": [],
        // "@typescript-eslint/no-unnecessary-type-arguments": [],
        // "@typescript-eslint/no-unnecessary-type-assertion": [],
        // "@typescript-eslint/no-unnecessary-type-conversion": [],
        // "@typescript-eslint/no-unnecessary-type-parameters": [],
        // "@typescript-eslint/no-unsafe-argument": [],
        // "@typescript-eslint/no-unsafe-assignment": [],
        // "@typescript-eslint/no-unsafe-call": [],
        // "@typescript-eslint/no-unsafe-enum-comparison": [],
        // "@typescript-eslint/no-unsafe-member-access": [],
        // "@typescript-eslint/no-unsafe-return": [],
        // "@typescript-eslint/no-unsafe-type-assertion": [],
        // "@typescript-eslint/no-unsafe-unary-minus": [],
        // "@typescript-eslint/no-use-before-define": [],
        // "@typescript-eslint/no-useless-empty-export": [],
        // "@typescript-eslint/non-nullable-type-assertion-style": [],
        // "@typescript-eslint/only-throw-error": [],
        // "@typescript-eslint/parameter-properties": [],
        // "@typescript-eslint/prefer-destructuring": [],
        // "@typescript-eslint/prefer-enum-initializers": [],
        // "@typescript-eslint/prefer-find": [],
        // "@typescript-eslint/prefer-for-of": [],
        // "@typescript-eslint/prefer-function-type": [],
        // "@typescript-eslint/prefer-includes": [],
        // "@typescript-eslint/prefer-nullish-coalescing": [],
        // "@typescript-eslint/prefer-optional-chain": [],
        // "@typescript-eslint/prefer-promise-reject-errors": [],
        // "@typescript-eslint/prefer-readonly": [],
        // "@typescript-eslint/prefer-readonly-parameter-types": [],
        // "@typescript-eslint/prefer-reduce-type-parameter": [],
        // "@typescript-eslint/prefer-regexp-exec": [],
        // "@typescript-eslint/prefer-return-this-type": [],
        // "@typescript-eslint/prefer-string-starts-ends-with": [],
        // "@typescript-eslint/promise-function-async": [],
        // "@typescript-eslint/related-getter-setter-pairs": [],
        // "@typescript-eslint/require-array-sort-compare": [],
        // "@typescript-eslint/require-await": [],
        // "@typescript-eslint/restrict-plus-operands": [],
        // "@typescript-eslint/restrict-template-expressions": [],
        // "@typescript-eslint/return-await": [],
        // "@typescript-eslint/strict-boolean-expressions": [],
        // "@typescript-eslint/switch-exhaustiveness-check": [],
        // "@typescript-eslint/unbound-method": [],
        // "@typescript-eslint/use-unknown-in-catch-callback-variable": [],
    },
});