import typescriptParser from "@typescript-eslint/parser";
import vueParser from "vue-eslint-parser";

// eslint-disable-next-line import/extensions
import { defineFlatConfigs } from "../.nuxt/eslint.config.mjs";

export default defineFlatConfigs({
    files: ["**/*.vue"],
    languageOptions: {
        parser: vueParser,
        parserOptions: {
            parser: typescriptParser,
            ecmaVersion: "latest",
            sourceType: "module",
            extraFileExtensions: [".vue"],
        },
    },
    rules: {
        "vue/html-indent": ["warn", 4],
        "vue/html-quotes": ["warn", "double"],
        "vue/attribute-hyphenation": ["warn", "never"],
        "vue/component-definition-name-casing": ["warn", "PascalCase"],
        "vue/component-name-in-template-casing": ["warn", "PascalCase"],
        "vue/multi-word-component-names": "off",
        "vue/require-default-prop": "error",
        "vue/require-prop-types": "error",
        "vue/no-mutating-props": "error",
        "vue/no-v-html": "error",
        "vue/max-attributes-per-line": ["warn", { singleline: 3, multiline: 1 }],
        "vue/order-in-components": "warn",
        "vue/v-on-style": ["warn", "shorthand"],
        "vue/v-bind-style": ["warn", "shorthand"],
        "vue/prop-name-casing": ["warn", "camelCase"],
        "vue/no-unused-components": "error",

        // Additional Vue rules (commented out with default values)
        // "vue/array-bracket-newline": [],
        // "vue/array-element-newline": [],
        // "vue/block-lang": [],
        // "vue/camelcase": [],
        // "vue/component-api-style": [],
        // "vue/component-options-name-casing": [],
        // "vue/custom-event-name-casing": [],
        // "vue/define-emits-declaration": [],
        // "vue/define-macros-order": [],
        // "vue/define-props-declaration": [],
        // "vue/define-props-destructuring": [],
        // "vue/dot-location": [],
        // "vue/dot-notation": [],
        // "vue/enforce-style-attribute": [],
        // "vue/eqeqeq": [],
        // "vue/func-call-spacing": [],
        // "vue/html-button-has-type": [],
        // "vue/html-comment-content-newline": [],
        // "vue/html-comment-indent": [],
        // "vue/match-component-file-name": [],
        // "vue/match-component-import-name": [],
        // "vue/max-len": [],
        // "vue/max-lines-per-block": [],
        // "vue/max-props": [],
        // "vue/max-template-depth": [],
        // "vue/multiline-ternary": [],
        // "vue/new-line-between-multi-line-property": [],
        // "vue/next-tick-style": [],
        // "vue/no-bare-strings-in-template": [],
        // "vue/no-boolean-default": [],
        // "vue/no-console": [],
        // "vue/no-constant-condition": [],
        // "vue/no-custom-modifiers-on-v-model": [],
        // "vue/no-duplicate-attr-inheritance": [],
        // "vue/no-empty-component-block": [],
        // "vue/no-empty-pattern": [],
        // "vue/no-extra-parens": [],
        // "vue/no-implicit-coercion": [],
        // "vue/no-import-compiler-macros": [],
        // "vue/no-irregular-whitespace": [],
        // "vue/no-loss-of-precision": [],
        // "vue/no-multiple-objects-in-class": [],
        // "vue/no-negated-condition": [],
        // "vue/no-negated-v-if-condition": [],
        // "vue/no-potential-component-option-typo": [],
        // "vue/no-ref-object-reactivity-loss": [],
        // "vue/no-restricted-block": [],
        // "vue/no-restricted-call-after-await": [],
        // "vue/no-restricted-class": [],
        // "vue/no-restricted-component-names": [],
        // "vue/no-restricted-component-options": [],
        // "vue/no-restricted-custom-event": [],
        // "vue/no-restricted-html-elements": [],
        // "vue/no-restricted-props": [],
        // "vue/no-restricted-static-attribute": [],
        // "vue/no-restricted-syntax": [],
        // "vue/no-restricted-v-bind": [],
        // "vue/no-restricted-v-on": [],
        // "vue/no-root-v-if": [],
        // "vue/no-setup-props-reactivity-loss": [],
        // "vue/no-sparse-arrays": [],
        // "vue/no-static-inline-styles": [],
        // "vue/no-template-target-blank": [],
        // "vue/no-this-in-before-route-enter": [],
        // "vue/no-undef-components": [],
        // "vue/no-undef-properties": [],
        // "vue/no-unsupported-features": [],
        // "vue/no-unused-emit-declarations": [],
        // "vue/no-unused-properties": [],
        // "vue/no-unused-refs": [],
        // "vue/no-use-v-else-with-v-for": [],
        // "vue/no-useless-concat": [],
        // "vue/no-useless-mustaches": [],
        // "vue/no-useless-v-bind": [],
        // "vue/no-v-text": [],
        // "vue/object-shorthand": [],
        // "vue/padding-line-between-tags": [],
        // "vue/padding-lines-in-component-definition": [],
        // "vue/prefer-define-options": [],
        // "vue/prefer-prop-type-boolean-first": [],
        // "vue/prefer-separate-static-class": [],
        // "vue/prefer-template": [],
        // "vue/prefer-true-attribute-shorthand": [],
        // "vue/prefer-use-template-ref": [],
        // "vue/require-default-export": [],
        // "vue/require-direct-export": [],
        // "vue/require-emit-validator": [],
        // "vue/require-explicit-slots": [],
        // "vue/require-expose": [],
        // "vue/require-macro-variable-name": [],
        // "vue/require-name-property": [],
        // "vue/require-prop-comment": [],
        // "vue/require-typed-object-prop": [],
        // "vue/require-typed-ref": [],
        // "vue/restricted-component-names": [],
        // "vue/script-indent": [],
        // "vue/slot-name-casing": [],
        // "vue/sort-keys": [],
        // "vue/space-infix-ops": [],
        // "vue/space-unary-ops": [],
        // "vue/static-class-names-order": [],
        // "vue/v-for-delimiter-style": [],
        // "vue/v-if-else-key": [],
        // "vue/v-on-handler-style": [],
    },
});